"""
Dynamic Mixture of Agents MoA Layer Skill Client
Pure Python Standard Library implementation of Mixture-of-Agents (MoA) Architecture (Wang et al. Together AI).
Aggregates outputs from Layer N-1 sub-agents, scores pairwise semantic agreement,
and constructs synthesized prompt contexts for Layer N aggregators.
"""

from typing import List, Dict, Any, Tuple, Set


class MixtureOfAgentsLayer:
    """
    MoA Layer coordinating proposer agents and an aggregator agent.
    Layer N synthesizes insights across all Layer N-1 responses.
    """

    def __init__(self, layer_index: int = 1):
        self.layer_index = layer_index

    @staticmethod
    def _jaccard_similarity(t1: str, t2: str) -> float:
        w1 = set(t1.lower().split())
        w2 = set(t2.lower().split())
        if not w1 or not w2:
            return 0.0
        return len(w1 & w2) / len(w1 | w2)

    def aggregate_proposals(self, original_query: str, proposals: List[Dict[str, str]]) -> Dict[str, Any]:
        """
        Aggregate proposals from proposer agents.
        :param proposals: List of {"agent_id": str, "response": str}
        """
        if not proposals:
            raise ValueError("Proposals list cannot be empty")

        num_agents = len(proposals)
        n = num_agents

        # Compute pairwise agreement matrix
        agreement_scores = []
        for i in range(n):
            row_score = 0.0
            for j in range(n):
                if i != j:
                    row_score += self._jaccard_similarity(proposals[i]["response"], proposals[j]["response"])
            agreement_scores.append(row_score / (n - 1) if n > 1 else 1.0)

        # Build synthesized aggregator context prompt
        formatted_proposals = []
        for idx, p in enumerate(proposals):
            formatted_proposals.append(
                f"[Candidate Response {idx + 1} from {p.get('agent_id', f'Agent_{idx+1}')}]:\n{p['response']}"
            )

        aggregator_context = (
            f"You are the Lead Synthesizer for Mixture-of-Agents Layer {self.layer_index}.\n"
            f"User Query: {original_query}\n\n"
            f"Here are {num_agents} candidate responses generated by different autonomous agents:\n\n"
            + "\n\n---\n\n".join(formatted_proposals) + "\n\n"
            f"Synthesize the single best, factually grounded, and comprehensive response incorporating "
            f"the strengths of each candidate while resolving all contradictions."
        )

        best_candidate_idx = agreement_scores.index(max(agreement_scores)) if agreement_scores else 0

        return {
            "layer_index": self.layer_index,
            "proposers_count": num_agents,
            "aggregator_prompt": aggregator_context,
            "highest_consensus_agent": proposals[best_candidate_idx].get("agent_id"),
            "consensus_score": round(agreement_scores[best_candidate_idx], 3) if agreement_scores else 1.0,
            "mean_consensus": round(sum(agreement_scores) / n, 3) if agreement_scores else 1.0
        }
